### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by eyelly-wu** [pascalgn/npm-publish-action#35] opened 2021-01-07 15:30 UTC
The error screenshot is as follows
![image](https://user-images.githubusercontent.com/24505069/103910669-0fd05380-5140-11eb-95ba-1c24d89ff5a3.png)

I don't know what this is _process.env.GITHUB_EVENT_PATH_ in the source code. Does it need to be added manually?
![image](https://user-images.githubusercontent.com/24505069/103910420-c4b64080-513f-11eb-8a37-a7d06dccdcca.png)

**Comment by pascalgn** [comment] 2021-02-14 16:12
I think this is still not fixed, but the error is quite hard to reproduce and it's a long time since there was any activity here. I will close this issue for now, but if you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2021-02-14 16:12 UTC
