### ISSUE TITLE
Issue pushing tags

### ISSUE THREAD

**Issue by butlerx** [pascalgn/npm-publish-action#14] opened 2020-04-26 11:57 UTC
Just ran the workflow and error was encounter pushing git tag
```

Run pascalgn/npm-publish-action@1.2.0
  with:
    tag_name: v%s
    tag_message: v%s
    commit_pattern: ^Release (\S+)
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    GITHUB_TOKEN: ***
    NPM_AUTH_TOKEN: ***
/usr/bin/docker run --name c27d3151de9bc9f5804b0dace65fe3f1d9933d_bb0f62 --label c27d31 --workdir /github/workspace --rm -e NPM_CONFIG_USERCONFIG -e NODE_AUTH_TOKEN -e GITHUB_TOKEN -e NPM_AUTH_TOKEN -e INPUT_TAG_NAME -e INPUT_TAG_MESSAGE -e INPUT_COMMIT_PATTERN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/gatsby-source-google-spreadsheets/gatsby-source-google-spreadsheets":"/github/workspace" c27d31:51de9bc9f5804b0dace65fe3f1d9933d
Found commit: Release 3.0.3
Executing: git rev-parse -q --verify refs/tags/v3.0.3
Executing: git config user.name butlerx
Executing: git config user.email butlerx@notthe.cloud
Executing: git tag -a -m v3.0.3 v3.0.3
Executing: git push origin refs/tags/v3.0.3
command failed with code 128
fatal: could not read Username for 'https://github.com': No such device or address```

**Comment by pascalgn** [comment] 2020-04-28 10:05
This looks like a general issue, not a problem with this specific action.

**Comment by CostaFernando** [comment] 2020-05-29 20:24
I'm facing the same problem. Any progress here?

**Comment by pascalgn** [comment] 2020-07-21 05:30
So far, there is not enough information to reproduce the bug. It's not a general issue, as not all users face this problem. Does the error occur every time?

**Comment by pascalgn** [comment] 2020-10-25 19:34
I think this is not yet fixed, or at least it's not clear what the cause for the problem is. However, it's a long time since there was some activity in this issue, so I will close it for now. If you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2020-10-25 19:34 UTC
